name: Get Secret From Vault

on:
    push:
        tags: ["v[0-9].[0-9]+.[0-9]+"]
        branches:
            - "development"
            - "staging"
            - "main"
    workflow_dispatch:

# jobs:
#     retrieve-secret:
#         runs-on: ubuntu-latest
#         permissions:
#             id-token: write
#             contents: read
#         steps:
#             - name: Retrieve secret from Vault
#               uses: hashicorp/vault-action@v2.4.0
#               with:
#                   exportToken: true # exports vault token as env variable; optional
#                   method: jwt
#                   url: https://vaultcluster-public-vault-4e04a4d0.810def75.z1.hashicorp.cloud:8200
#                   role: github-actions # vault role name
#                   secrets: secret/data/github-actions hello # vault secret path
#                   namespace: admin

#             - name: Use secret from Vault
#               if: always()
#               run: |
#                   echo "secret: $HELLO ; vault token: $VAULT_TOKEN."

jobs:
    retrieve-secret:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Retrieve secret from Vault
              uses: hashicorp/vault-action@v2.4.0
              with:
                  exportToken: true
                  method: jwt
                  url: https://vaultcluster-public-vault-4e04a4d0.810def75.z1.hashicorp.cloud:8200
                  namespace: admin
                  role: myproject-production
                  secrets: secret/data/production/ci hello

            - name: Use secret from Vault
              run: |
                  echo "secret: $HELLO ; vault token: $VAULT_TOKEN."
